// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ

#include "../ui.h"

void ui_ScreenPageEasterEgg_screen_init(void)
{
    ui_ScreenPageEasterEgg = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPageEasterEgg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenPageEasterEgg, 466, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenPageEasterEgg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPageEasterEgg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerEasterEgg = lv_spinner_create(ui_ScreenPageEasterEgg, 1000, 90);
    lv_obj_set_width(ui_SpinnerEasterEgg, 466);
    lv_obj_set_height(ui_SpinnerEasterEgg, 466);
    lv_obj_set_align(ui_SpinnerEasterEgg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerEasterEgg, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_SpinnerEasterEgg, lv_color_hex(  COLOR_DOMIANT_PINK), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerEasterEgg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerEasterEgg, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SpinnerEasterEgg, lv_color_hex(  COLOR_DOMIANT_PINK), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerEasterEgg, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerEasterEgg, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ScreenArcPageEasterEgg = lv_arc_create(ui_ScreenPageEasterEgg);
    lv_obj_set_width(ScreenArcPageEasterEgg, 440);
    lv_obj_set_height(ScreenArcPageEasterEgg, 440);
    lv_obj_set_align(ScreenArcPageEasterEgg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ScreenArcPageEasterEgg, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ScreenArcPageEasterEgg, 0);
    lv_arc_set_bg_angles(ScreenArcPageEasterEgg, 0, 360);
    lv_obj_set_style_arc_color(ScreenArcPageEasterEgg, lv_color_hex(  COLOR_SECONDARY_PINK), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ScreenArcPageEasterEgg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ScreenArcPageEasterEgg, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ScreenArcPageEasterEgg, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ScreenArcPageEasterEgg, lv_color_hex(  COLOR_DOMIANT_PINK), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ScreenArcPageEasterEgg, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ScreenArcPageEasterEgg, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ScreenArcPageEasterEgg, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ScreenArcPageEasterEgg, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ScreenArcPageEasterEgg, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

#if USE_GIF_EASTER_EGG == 1
    imageEasterEgg = lv_gif_create(ui_ScreenPageEasterEgg);
    lv_gif_set_src(imageEasterEgg, &gifCuteCatZip);
    lv_obj_align(imageEasterEgg, LV_ALIGN_CENTER, 0, 0);
#else
    imageEasterEgg = lv_img_create(ui_ScreenPageEasterEgg);
    lv_img_set_src(imageEasterEgg, &pngLogoMITSUBISHI);
    lv_obj_set_width(imageEasterEgg, LV_SIZE_CONTENT);   /// 400
    lv_obj_set_height(imageEasterEgg, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_align(imageEasterEgg, LV_ALIGN_CENTER);
    lv_obj_set_y(imageEasterEgg, -20);
#endif

    lv_obj_add_event_cb(ScreenArcPageEasterEgg, ui_event_easter_egg_background, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenPageEasterEgg, ui_event_easter_egg_background, LV_EVENT_GESTURE, NULL);
}
