// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ

#include "../ui.h"

void ui_ScreenPageMain_screen_init(void)
{
    ui_ScreenPageMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPageMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenPageMain, 466, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenPageMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPageMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageMainPageback = lv_img_create(ui_ScreenPageMain);
    lv_img_set_src(ui_ImageMainPageback, &ui_img_pngmainback_png);
    lv_obj_set_width(ui_ImageMainPageback, LV_SIZE_CONTENT);   /// 400
    lv_obj_set_height(ui_ImageMainPageback, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_align(ui_ImageMainPageback, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageMainPageback, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMainPageback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpinnerMainPage = lv_spinner_create(ui_ScreenPageMain, 1000, 90);
    lv_obj_set_width(ui_SpinnerMainPage, 466);
    lv_obj_set_height(ui_SpinnerMainPage, 466);
    lv_obj_set_align(ui_SpinnerMainPage, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerMainPage, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_SpinnerMainPage, lv_color_hex( COLOR_DOMIANT_PINK), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerMainPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerMainPage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SpinnerMainPage, lv_color_hex( COLOR_DOMIANT_PINK), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerMainPage, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerMainPage, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ArcGeningRpm = lv_arc_create(ui_ScreenPageMain);
    lv_obj_set_width(ui_ArcGeningRpm, 440);
    lv_obj_set_height(ui_ArcGeningRpm, 440);
    lv_obj_set_align(ui_ArcGeningRpm, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcGeningRpm, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_ArcGeningRpm, 50);
    lv_arc_set_bg_angles(ui_ArcGeningRpm, 155, 265);
    lv_obj_set_style_arc_color(ui_ArcGeningRpm, lv_color_hex( COLOR_SECONDARY_PINK), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcGeningRpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcGeningRpm, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcGeningRpm, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcGeningRpm, lv_color_hex( COLOR_DOMIANT_PINK), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcGeningRpm, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcGeningRpm, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcGeningRpm, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcGeningRpm, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcGeningRpm, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcCarSpeed = lv_arc_create(ui_ScreenPageMain);
    lv_obj_set_width(ui_ArcCarSpeed, 440);
    lv_obj_set_height(ui_ArcCarSpeed, 440);
    lv_obj_set_align(ui_ArcCarSpeed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcCarSpeed, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_ArcCarSpeed, 50);
    lv_arc_set_bg_angles(ui_ArcCarSpeed, 275, 25);
    lv_arc_set_mode(ui_ArcCarSpeed, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_color(ui_ArcCarSpeed, lv_color_hex( COLOR_SECONDARY_PINK), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcCarSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcCarSpeed, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcCarSpeed, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcCarSpeed, lv_color_hex( COLOR_DOMIANT_PINK), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcCarSpeed, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcCarSpeed, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcCarSpeed, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcCarSpeed, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcCarSpeed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcGearNumBack = lv_arc_create(ui_ScreenPageMain);
    lv_obj_set_width(ui_ArcGearNumBack, 440);
    lv_obj_set_height(ui_ArcGearNumBack, 440);
    lv_obj_set_align(ui_ArcGearNumBack, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcGearNumBack, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_ArcGearNumBack, 60);
    lv_arc_set_bg_angles(ui_ArcGearNumBack, 35, 145);
    lv_arc_set_mode(ui_ArcGearNumBack, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_color(ui_ArcGearNumBack, lv_color_hex( COLOR_SECONDARY_PINK), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcGearNumBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcGearNumBack, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcGearNumBack, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcGearNumBack, lv_color_hex( COLOR_DOMIANT_PINK), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcGearNumBack, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcGearNumBack, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcGearNumBack, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcGearNumBack, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcGearNumBack, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelGeningRpmText = lv_label_create(ui_ScreenPageMain);
    lv_obj_set_width(ui_LabelGeningRpmText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGeningRpmText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGeningRpmText, -90);
    lv_obj_set_y(ui_LabelGeningRpmText, -55);
    lv_obj_set_align(ui_LabelGeningRpmText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGeningRpmText, "2000");
    lv_obj_set_style_text_color(ui_LabelGeningRpmText, lv_color_hex( COLOR_DOMIANT_PINK), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGeningRpmText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelGeningRpmText, &ui_font_FontTaikongSize64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGeningRpmUnitText = lv_label_create(ui_ScreenPageMain);
    lv_obj_set_width(ui_LabelGeningRpmUnitText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGeningRpmUnitText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGeningRpmUnitText, -100);
    lv_obj_set_y(ui_LabelGeningRpmUnitText, 0);
    lv_obj_set_align(ui_LabelGeningRpmUnitText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGeningRpmUnitText, "rpm");
    lv_obj_set_style_text_color(ui_LabelGeningRpmUnitText, lv_color_hex( COLOR_DOMIANT_PINK), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGeningRpmUnitText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelGeningRpmUnitText, &ui_font_FontTaikongSize32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCarSpeedText = lv_label_create(ui_ScreenPageMain);
    lv_obj_set_width(ui_LabelCarSpeedText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCarSpeedText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCarSpeedText, 90);
    lv_obj_set_y(ui_LabelCarSpeedText, -55);
    lv_obj_set_align(ui_LabelCarSpeedText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCarSpeedText, "45");
    lv_obj_set_style_text_color(ui_LabelCarSpeedText, lv_color_hex( COLOR_DOMIANT_PINK), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCarSpeedText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCarSpeedText, &ui_font_FontTaikongSize64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCarSpeedUnitText = lv_label_create(ui_ScreenPageMain);
    lv_obj_set_width(ui_LabelCarSpeedUnitText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCarSpeedUnitText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCarSpeedUnitText, 100);
    lv_obj_set_y(ui_LabelCarSpeedUnitText, 0);
    lv_obj_set_align(ui_LabelCarSpeedUnitText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCarSpeedUnitText, "km/h");
    lv_obj_set_style_text_color(ui_LabelCarSpeedUnitText, lv_color_hex( COLOR_DOMIANT_PINK), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCarSpeedUnitText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCarSpeedUnitText, &ui_font_FontTaikongSize32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerMainPageBottomBlock = lv_obj_create(ui_ScreenPageMain);
    lv_obj_remove_style_all(ui_ContainerMainPageBottomBlock);
    lv_obj_set_width(ui_ContainerMainPageBottomBlock, 320);
    lv_obj_set_height(ui_ContainerMainPageBottomBlock, 130);
    lv_obj_set_x(ui_ContainerMainPageBottomBlock, 0);
    lv_obj_set_y(ui_ContainerMainPageBottomBlock, 115);
    lv_obj_set_align(ui_ContainerMainPageBottomBlock, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerMainPageBottomBlock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelGearNumText = lv_label_create(ui_ContainerMainPageBottomBlock);
    lv_obj_set_width(ui_LabelGearNumText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGearNumText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelGearNumText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGearNumText, "N");
    lv_obj_set_style_text_color(ui_LabelGearNumText, lv_color_hex(0xCF08EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGearNumText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelGearNumText, &ui_font_FontBabySize56, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerMainPageMlieageBlock = lv_obj_create(ui_ContainerMainPageBottomBlock);
    lv_obj_remove_style_all(ui_ContainerMainPageMlieageBlock);
    lv_obj_set_width(ui_ContainerMainPageMlieageBlock, 320);
    lv_obj_set_height(ui_ContainerMainPageMlieageBlock, 130);
    lv_obj_set_align(ui_ContainerMainPageMlieageBlock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerMainPageMlieageBlock, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerMainPageMlieageBlock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelMainMlieageText = lv_label_create(ui_ContainerMainPageMlieageBlock);
    lv_obj_set_width(ui_LabelMainMlieageText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMainMlieageText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMainMlieageText, 0);
    lv_obj_set_y(ui_LabelMainMlieageText, 25);
    lv_obj_set_align(ui_LabelMainMlieageText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMainMlieageText, "2000.0");
    lv_obj_set_style_text_color(ui_LabelMainMlieageText, lv_color_hex(0xCF08EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMainMlieageText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMainMlieageText, &ui_font_FontTaikongSize64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMainMieageNum = lv_label_create(ui_ContainerMainPageMlieageBlock);
    lv_obj_set_width(ui_LabelMainMieageNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMainMieageNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMainMieageNum, 0);
    lv_obj_set_y(ui_LabelMainMieageNum, -40);
    lv_obj_set_align(ui_LabelMainMieageNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMainMieageNum, "TRIP");
    lv_obj_set_style_text_color(ui_LabelMainMieageNum, lv_color_hex(0xCF08EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMainMieageNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMainMieageNum, &ui_font_FontTaikongSize32, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_add_event_cb(ui_ArcGearNumBack, ui_event_main_background, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenPageMain, ui_event_main_background, LV_EVENT_GESTURE, NULL);

}
