// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ

#include "../ui.h"

void ui_ScreenPageEasterEgg_screen_init(void)
{
    ui_ScreenPageEasterEgg = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPageEasterEgg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenPageEasterEgg, 466, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenPageEasterEgg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPageEasterEgg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

#if USE_GIF_EASTER_EGG == 1
    imageEasterEgg = lv_gif_create(ui_ScreenPageEasterEgg);
    lv_gif_set_src(imageEasterEgg, &gifKaBiBaLaZip);
    lv_obj_align(imageEasterEgg, LV_ALIGN_CENTER, 0, 0);
#else
    imageEasterEgg = lv_img_create(ui_ScreenPageEasterEgg);
    lv_img_set_src(imageEasterEgg, &pngLogoMITSUBISHI);
    lv_obj_set_width(imageEasterEgg, LV_SIZE_CONTENT);   /// 400
    lv_obj_set_height(imageEasterEgg, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_align(imageEasterEgg, LV_ALIGN_CENTER);
    lv_obj_set_y(imageEasterEgg, -20);
#endif

    // ui_SpinnerEasterEgg = lv_spinner_create(ui_ScreenPageEasterEgg, 1000, 90);
    // lv_obj_set_width(ui_SpinnerEasterEgg, 466);
    // lv_obj_set_height(ui_SpinnerEasterEgg, 466);
    // lv_obj_set_align(ui_SpinnerEasterEgg, LV_ALIGN_CENTER);
    // lv_obj_clear_flag(ui_SpinnerEasterEgg, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    // lv_obj_set_style_arc_color(ui_SpinnerEasterEgg, lv_color_hex(0xCC03C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_opa(ui_SpinnerEasterEgg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_width(ui_SpinnerEasterEgg, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_set_style_arc_color(ui_SpinnerEasterEgg, lv_color_hex(0xCC03C8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_opa(ui_SpinnerEasterEgg, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_width(ui_SpinnerEasterEgg, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // ArcPageEasterEggBack = lv_arc_create(ui_ScreenPageEasterEgg);
    // lv_obj_set_width(ArcPageEasterEggBack, 440);
    // lv_obj_set_height(ArcPageEasterEggBack, 440);
    // lv_obj_set_align(ArcPageEasterEggBack, LV_ALIGN_CENTER);
    // lv_obj_clear_flag(ArcPageEasterEggBack, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    // lv_arc_set_value(ArcPageEasterEggBack, 0);
    // lv_arc_set_bg_angles(ArcPageEasterEggBack, 0, 360);
    // lv_obj_set_style_arc_color(ArcPageEasterEggBack, lv_color_hex(0x410641), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_opa(ArcPageEasterEggBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_width(ArcPageEasterEggBack, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_rounded(ArcPageEasterEggBack, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_set_style_arc_color(ArcPageEasterEggBack, lv_color_hex(0xCC03C8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_opa(ArcPageEasterEggBack, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_width(ArcPageEasterEggBack, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // lv_obj_set_style_arc_rounded(ArcPageEasterEggBack, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // lv_obj_set_style_bg_color(ArcPageEasterEggBack, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ArcPageEasterEggBack, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    // ui_ImageEggBlackEar = lv_img_create(ui_ScreenPageEasterEgg);
    // lv_img_set_src(ui_ImageEggBlackEar, &ui_img_pngblackear_png);
    // lv_obj_set_width(ui_ImageEggBlackEar, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_ImageEggBlackEar, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_ImageEggBlackEar, 0);
    // lv_obj_set_y(ui_ImageEggBlackEar, -142);
    // lv_obj_set_align(ui_ImageEggBlackEar, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_ImageEggBlackEar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    // lv_obj_clear_flag(ui_ImageEggBlackEar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(imageEasterEgg, ui_event_easter_egg_background, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenPageEasterEgg, ui_event_easter_egg_background, LV_EVENT_GESTURE, NULL);
   
   
}
