// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ

#include "../ui.h"

void ui_ScreenPageGear_screen_init(void)
{
    ui_ScreenPageGear = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPageGear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenPageGear, 466, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenPageGear, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPageGear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerGearPage = lv_spinner_create(ui_ScreenPageGear, 1000, 90);
    lv_obj_set_width(ui_SpinnerGearPage, 466);
    lv_obj_set_height(ui_SpinnerGearPage, 466);
    lv_obj_set_align(ui_SpinnerGearPage, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerGearPage, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_SpinnerGearPage, lv_color_hex(0xCC03C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerGearPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerGearPage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SpinnerGearPage, lv_color_hex(0xCC03C8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerGearPage, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerGearPage, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_GearPageArcLabelGearNumText = lv_label_create(ui_ScreenPageGear);
    lv_obj_set_width(ui_GearPageArcLabelGearNumText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GearPageArcLabelGearNumText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GearPageArcLabelGearNumText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GearPageArcLabelGearNumText, "N");
    lv_obj_set_style_text_color(ui_GearPageArcLabelGearNumText, lv_color_hex(0xCC03C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GearPageArcLabelGearNumText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GearPageArcLabelGearNumText, &ui_font_FontBabySize156, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GearPageArcGearNumBack = lv_arc_create(ui_ScreenPageGear);
    lv_obj_set_width(ui_GearPageArcGearNumBack, 440);
    lv_obj_set_height(ui_GearPageArcGearNumBack, 440);
    lv_obj_set_align(ui_GearPageArcGearNumBack, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GearPageArcGearNumBack, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_GearPageArcGearNumBack, 0);
    lv_arc_set_bg_angles(ui_GearPageArcGearNumBack, 0, 360);
    lv_obj_set_style_arc_color(ui_GearPageArcGearNumBack, lv_color_hex(0x410641), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_GearPageArcGearNumBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_GearPageArcGearNumBack, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_GearPageArcGearNumBack, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_GearPageArcGearNumBack, lv_color_hex(0xCC03C8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_GearPageArcGearNumBack, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_GearPageArcGearNumBack, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_GearPageArcGearNumBack, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_GearPageArcGearNumBack, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GearPageArcGearNumBack, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImageGearBlackEar = lv_img_create(ui_ScreenPageGear);
    lv_img_set_src(ui_ImageGearBlackEar, &ui_img_pngblackear_png);
    lv_obj_set_width(ui_ImageGearBlackEar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGearBlackEar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGearBlackEar, 0);
    lv_obj_set_y(ui_ImageGearBlackEar, -142);
    lv_obj_set_align(ui_ImageGearBlackEar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageGearBlackEar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGearBlackEar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_GearPageArcGearNumBack, ui_event_gear_background, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenPageGear, ui_event_gear_background, LV_EVENT_GESTURE, NULL);

}
