// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: HF-ESP-10-7-OLED

#include "../ui.h"
#include "lvgl.h"
#include <stdio.h>
// 声明全局变量来存储进度条的值  
static int bar_value = 0;  
 int selected_index=0;
 extern  char * options[];
 extern  int options2[];
 extern int HF_ui_screen_id;
  int HF_number=15;//最初
// 定时器回调函数，用于更新进度条的值  
lv_timer_t * bar_time=NULL;

static void bar_update_cb(lv_timer_t * timer)  
{  
  
    
    if(HF_ui_screen_id==3)
    {
       
       
        
        // 每次调用时增加进度条的值（可根据需要调整增量）  
        int i=options2[selected_index];
        
        // bar_value += 5;
        bar_value =bar_value+(100/i);
    
        // 若值达到或超过100，则重置为0（对于对称模式，您可能希望设置为某个最大值而非100）  
        if(bar_value >= 100) {  
        // lv_timer_pause(bar_time);
        bar_value = 0;  
         HF_ui_screen_id=1;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);
        }  
        //current_value
        // 更新进度条显示  
        
        lv_bar_set_value(ui_Bar2, bar_value, LV_ANIM_ON); // 启用动画效果  
        

        
        char num_str[16]={0}; // 对于32位整数来说，10个字符足够（包括负号和空字符）  
        
        //暂时不用了，不能和进度条反向同步
        // 使用snprintf将整数转换为字符串  
        // HF_number=(bar_value*i)/100;
        // snprintf(num_str, sizeof(num_str), "%d", bar_value);  
        
       
        // _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, num_str);
    }
    else
    {
      bar_value = 0;  
      lv_bar_set_value(ui_Bar2, 0, LV_ANIM_ON); // 启用动画效果    
    }
}  
void ui_working_screen_init(void)
{
    ui_working = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_working, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_working);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -63);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "15");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_working);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -141);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "working");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_working);
    lv_bar_set_mode(ui_Bar2, LV_BAR_MODE_SYMMETRICAL);
    lv_bar_set_value(ui_Bar2, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 300);
    lv_obj_set_height(ui_Bar2, 25);
    lv_obj_set_x(ui_Bar2, -8);
    lv_obj_set_y(ui_Bar2, 22);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xFF4500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_working);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 100);
    lv_obj_set_x(ui_Button3, 0);
    lv_obj_set_y(ui_Button3, 132);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xE64500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_working);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 127);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "stop");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner3 = lv_spinner_create(ui_working, 1000, 90);
    lv_obj_set_width(ui_Spinner3, 460);
    lv_obj_set_height(ui_Spinner3, 460);
    lv_obj_set_align(ui_Spinner3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner3, lv_color_hex(0xE64500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner3, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

    bar_time=lv_timer_create(bar_update_cb, 1000, NULL); // 每秒调用一次bar_update_cb函数

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
