// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ

#include "ui.h"
#include "ui_helpers.h"
#include <driver/gpio.h>
#include "../bsp_board.h"


static const char *TAG = "ui";
///////////////////// VARIABLES ////////////////////
void ui_ScreenPageLogo_screen_init(void);
lv_obj_t * ui_ScreenPageLogo;
lv_obj_t * gif_logo;

// SCREEN: ui_ScreenPageMain
void ui_ScreenPageMain_screen_init(void);
lv_obj_t * ui_ScreenPageMain;
lv_obj_t * ui_Image1;
lv_obj_t * ui_SpinnerMainPage;
lv_obj_t * ui_ArcGeningRpm;
lv_obj_t * ui_ArcCarSpeed;
lv_obj_t * ui_ArcGearNumBack;
lv_obj_t * ui_ArcGearNumMask;
lv_obj_t * ui_LabelGearNumText;
lv_obj_t * ui_LabelGeningRpmText;
lv_obj_t * ui_LabelGeningRpmUnitText;
lv_obj_t * ui_LabelCarSpeedText;
lv_obj_t * ui_LabelCarSpeedUnitText;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageGear
void ui_ScreenPageGear_screen_init(void);
lv_obj_t * ui_ScreenPageGear;
lv_obj_t * ui_SpinnerMainPage1;
lv_obj_t * ui_ArcGearNumBack1;
lv_obj_t * ui_LabelGearNumText1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_pngmainback[2] = {&ui_img_pngmainback2_png, &ui_img_pngmainback3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////

void my_timerMain(lv_timer_t * timer)
{
    char *pGearNum[] = {"N","1", "2", "3", "4", "5"};
    static uint16_t usRpm = 0;
    static uint8_t ucSpeed = 0;
    static uint8_t ucOnlyOnce = 0;
    static uint32_t ulOpenLightTimeCnt = 0;
    usRpm   = obd_data_get_rpm();
    ucSpeed = obd_data_get_speed();
    lv_label_set_text_fmt(ui_LabelGeningRpmText, "%d", usRpm);
    lv_label_set_text_fmt(ui_LabelCarSpeedText, "%d", ucSpeed);
    lv_arc_set_value(ui_ArcGeningRpm, (uint32_t)usRpm*100/7000);
    lv_arc_set_value(ui_ArcCarSpeed, (uint16_t)ucSpeed*100/200);
    lv_label_set_text_fmt (ui_LabelGearNumText, pGearNum[calculate_gear(usRpm, ucSpeed)]);

// #if EXAMPLE_PIN_NUM_BK_LIGHT >= 0
//         //等待500ms后开背光，避免没有初始化完成就开背光，只执行一次
//         if(ucOnlyOnce == 0)
//         {
//             if(ulOpenLightTimeCnt > 400 / 200)
//             {
//                 gpio_set_level(EXAMPLE_PIN_NUM_BK_LIGHT, EXAMPLE_LCD_BK_LIGHT_ON_LEVEL);
//                 ESP_LOGI(TAG, "Turn on LCD backlight");
//                 ulOpenLightTimeCnt = 0;
//                 ucOnlyOnce = 1;//只执行一次
//             }
//         }
// #endif
}
///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////



///////////////////// FUNCTIONS ////////////////////
void ui_event_logo_background(lv_event_t * e)
{  
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {//触摸点击
        ESP_LOGI(TAG, "Logo LV_EVENT_CLICKED ! \n");

        _ui_screen_change(&ui_ScreenPageMain, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageMain_screen_init);  
        lv_obj_del(gif_logo); //一定要手动删除gif，切换页面不会删除gif，不然占用资源
    }   
}


///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenPageLogo_screen_init();
    ui_ScreenPageMain_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenPageLogo);

    lv_timer_create(my_timerMain, 200, NULL);  //200 ms 周期
}
