// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"


static const char *TAG = "ui";
///////////////////// VARIABLES ////////////////////
void ui_ScreenPageLogo_screen_init(void);
lv_obj_t * ui_ScreenPageLogo;
lv_obj_t * gif_logo;

// SCREEN: ui_ScreenPageMain
void ui_ScreenPageMain_screen_init(void);
lv_obj_t * ui_ScreenPageMain;
lv_obj_t * ui_Image1;
lv_obj_t * ui_SpinnerMainPage;
lv_obj_t * ui_ArcGeningRpm;
lv_obj_t * ui_ArcCarSpeed;
lv_obj_t * ui_ArcGearNumBack;
lv_obj_t * ui_ArcGearNumMask;
lv_obj_t * ui_LabelGearNumText;
lv_obj_t * ui_LabelGeningRpmText;
lv_obj_t * ui_LabelGeningRpmUnitText;
lv_obj_t * ui_LabelCarSpeedText;
lv_obj_t * ui_LabelCarSpeedUnitText;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_pngmainback[2] = {&ui_img_pngmainback2_png, &ui_img_pngmainback3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////

void my_timerMain(lv_timer_t * timer)
{
    static uint16_t usRpm = 0;
    static uint8_t ucSpeed = 0;
    usRpm   = obd_data_get_rpm();
    ucSpeed = obd_data_get_speed();
    lv_label_set_text_fmt(ui_LabelGeningRpmText, "%d", usRpm);
    lv_label_set_text_fmt(ui_LabelCarSpeedText, "%d", ucSpeed);
    lv_arc_set_value(ui_ArcGeningRpm, (uint32_t)usRpm*100/7000);
    lv_arc_set_value(ui_ArcCarSpeed, (uint16_t)ucSpeed*100/200);
}
///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////



///////////////////// FUNCTIONS ////////////////////
void ui_event_logo_background(lv_event_t * e)
{  
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {//触摸点击
        ESP_LOGI(TAG, "Logo LV_EVENT_CLICKED ! \n");

        _ui_screen_change(&ui_ScreenPageMain, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageMain_screen_init);  
        lv_obj_del(gif_logo); //一定要手动删除gif，切换页面不会删除gif，不然占用资源
    }   
}

void btn1_event_handler(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {//触摸点击
        ESP_LOGI(TAG, "Main LV_EVENT_CLICKED ! \n");
    }  
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenPageLogo_screen_init();
    ui_ScreenPageMain_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenPageLogo);

    lv_timer_t * timerMain;
    timerMain = lv_timer_create(my_timerMain, 200, NULL);  //第二个参数（周期）是以毫秒为单位
}
