// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenPageMain
void ui_ScreenPageMain_screen_init(void);
lv_obj_t * ui_ScreenPageMain;
lv_obj_t * ui_Image1;
lv_obj_t * ui_SpinnerMainPage;
lv_obj_t * ui_ArcGeningRpm;
lv_obj_t * ui_ArcCarSpeed;
lv_obj_t * ui_ArcGearNumBack;
lv_obj_t * ui_ArcGearNumMask;
lv_obj_t * ui_LabelGearNumText;
lv_obj_t * ui_LabelGeningRpmText;
lv_obj_t * ui_LabelGeningRpmUnitText;
lv_obj_t * ui_LabelCarSpeedText;
lv_obj_t * ui_LabelCarSpeedUnitText;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_pngmainback[2] = {&ui_img_pngmainback2_png, &ui_img_pngmainback3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////

void my_timerMain(lv_timer_t * timer)
{
    ESP_LOGI("my_timerMain", "my_timerMain called");
    lv_label_set_text_fmt(ui_LabelGeningRpmText, "%d", obd_data_get_rpm());
    lv_label_set_text_fmt(ui_LabelCarSpeedText, "%d", obd_data_get_speed());
}
///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void btn1_event_handler(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if (sec_conn) {
        if(code == LV_EVENT_PRESSING) {
            esp_hidd_send_consumer_value(hid_conn_id, HID_CONSUMER_VOLUME_DOWN, true);
            ESP_LOGI(HID_DEMO_TAG, "DOWN LV_EVENT_CLICKED");
        }
        else if(code == LV_EVENT_RELEASED) {
            esp_hidd_send_consumer_value(hid_conn_id, HID_CONSUMER_VOLUME_DOWN, false);
            ESP_LOGI(HID_DEMO_TAG, "DOWN LV_EVENT_RELEASED");
        }
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenPageMain_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenPageMain);

    lv_timer_t * timerMain;
    timerMain = lv_timer_create(my_timerMain, 1000, NULL);  //第二个参数（周期）是以毫秒为单位
}
