// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "bsp_ble/ble_hidd_demo.h"
#include "esp_log.h"
#include "obd_data_cache.h"


// SCREEN: ui_ScreenPageMain
void ui_ScreenPageMain_screen_init(void);
extern lv_obj_t * ui_ScreenPageMain;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_SpinnerMainPage;
extern lv_obj_t * ui_ArcGeningRpm;
extern lv_obj_t * ui_ArcCarSpeed;
extern lv_obj_t * ui_ArcGearNumBack;
extern lv_obj_t * ui_ArcGearNumMask;
extern lv_obj_t * ui_LabelGearNumText;
extern lv_obj_t * ui_LabelGeningRpmText;
extern lv_obj_t * ui_LabelGeningRpmUnitText;
extern lv_obj_t * ui_LabelCarSpeedText;
extern lv_obj_t * ui_LabelCarSpeedUnitText;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pngmainback3_png);    // assets/pngMainBack3.png
LV_IMG_DECLARE(ui_img_pngmainback2_png);    // assets/pngMainBack2.png

// FONTS
LV_FONT_DECLARE(ui_font_FontBabyGearNumSize48);
LV_FONT_DECLARE(ui_font_FontTaikongSize32);

// UI INIT
void ui_init(void);
void btn1_event_handler(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
