// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ

#ifndef _OBD_PRJ_UI_H
#define _OBD_PRJ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "bsp_ble/ble_hidd_demo.h"
#include "esp_log.h"
#include "obd_data_cache.h"


void ui_ScreenPageLogo_screen_init(void);
extern lv_obj_t * ui_ScreenPageLogo;
extern lv_obj_t * gif_logo;

// SCREEN: ui_ScreenPageMain
void ui_ScreenPageMain_screen_init(void);
extern lv_obj_t * ui_ScreenPageMain;
extern lv_obj_t * ui_ImageMainPageback;
extern lv_obj_t * ui_SpinnerMainPage;
extern lv_obj_t * ui_ArcGeningRpm;
extern lv_obj_t * ui_ArcCarSpeed;
extern lv_obj_t * ui_ArcGearNumBack;
extern lv_obj_t * ui_ArcGearNumMask;
extern lv_obj_t * ui_LabelGearNumText;
extern lv_obj_t * ui_LabelGeningRpmText;
extern lv_obj_t * ui_LabelGeningRpmUnitText;
extern lv_obj_t * ui_LabelCarSpeedText;
extern lv_obj_t * ui_LabelCarSpeedUnitText;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageGear
void ui_ScreenPageGear_screen_init(void);
extern lv_obj_t * ui_ScreenPageGear;
extern lv_obj_t * ui_SpinnerMainPage1;
extern lv_obj_t * ui_ArcGearNumBack1;
extern lv_obj_t * ui_LabelGearNumText1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;
LV_IMG_DECLARE(gifBlueLightLogo);    
LV_IMG_DECLARE(gifSnake400);  
// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pngmainback3_png);    // assets/pngMainBack3.png
LV_IMG_DECLARE(ui_img_pngmainback2_png);    // assets/pngMainBack2.png

// FONTS
LV_FONT_DECLARE(ui_font_FontBabyGearNumSize48);
LV_FONT_DECLARE(ui_font_FontBabySize108);
LV_FONT_DECLARE(ui_font_FontBabySize180);
LV_FONT_DECLARE(ui_font_FontBabySize200);
LV_FONT_DECLARE(ui_font_FontBabySize56);
LV_FONT_DECLARE(ui_font_FontTaikongSize32);
LV_FONT_DECLARE(ui_font_FontTaikongSize40);

// UI INIT
void ui_init(void);
void ui_event_logo_background(lv_event_t * e);
void ui_event_main_background(lv_event_t * e);
void ui_event_gear_background(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
