// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: HF-ESP-10-7-OLED

#include "ui.h"
#include "lvgl.h"
#include "ui_helpers.h"
#include "esp_log.h"

#include "iot_knob.h"
#include "iot_button.h"
///////////////////// VARIABLES ////////////////////
static const char *TAG = "ui";
extern  int selected_index;
extern  char * options[];
extern  char * options2[];
extern int options_max_num;
extern int HF_number;
///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_background(lv_event_t * e);
lv_obj_t * ui_background;
lv_obj_t * ui_Image12;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;


// SCREEN: ui_working
void ui_working_screen_init(void);
lv_obj_t * ui_working;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Bar2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Spinner3;


// SCREEN: ui_time
void ui_time_screen_init(void);
lv_obj_t * ui_time;
lv_obj_t * ui_Roller1;
lv_obj_t * ui_Image1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Image6;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_back[1] = {&ui_img_back111_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif
#include "led_strip.h"

//彩灯///
extern  led_strip_handle_t led_strip;
#define LED_STRIP_LED_NUMBERS 8
int color_RT=1;
uint32_t red=150;
uint32_t blue=0;
uint32_t green=0;

uint8_t color_num=150;
int color_change=0;
////
///////////////////// ANIMATIONS ////////////////////
static uint8_t index2=0;
//******************* */
 volatile int HF_botton;
 volatile int HF_botton_time;
 volatile int HF_encoder_num;
volatile static int num=1;
volatile static int HF_index=1;
uint8_t HF_ui_screen_id=1;//当前屏幕索引  1主界面  2设置时间  3工作
void  color_running()//呼吸灯，红绿蓝交替
{

if(color_change<3)
{
     if(color_RT==1)
   {
        red++;
        if(red>255)
        color_RT=-1;
   }
   else if(color_RT==-1)
   {
      
        red--;
        if(red<=0)
        {
          color_change++;  
          color_RT=1;
        }

   }
}
else if(color_change>=3&&color_change<6)
{
    {
     if(color_RT==1)
   {
        blue++;
        if(blue>255)
        color_RT=-1;
   }
   else if(color_RT==-1)
   {
      
        blue--;
        if(blue<=0)
        {
          color_change++;  
          color_RT=1;
        }

   }
  }
}

else if(color_change>=6&&color_change<9)
{
    {
     if(color_RT==1)
   {
        green++;
        if(green>255)
        color_RT=-1;
   }
   else if(color_RT==-1)
   {
      
        green--;
        if(green<=0)
        {
          color_change++;  
          color_RT=1;
        }

   }
  }
}
else if(color_change>=9)
{
  color_change=0;
  color_RT=1;
  red=150;

}

  // red=blue=green=0;
  //    red=color_num;
//    if(color_change<=3)
//    {
//       red=blue=green=0;
//       red=color_num;
//    }
//    else if(color_change>3&&color_change<6)
//    {
//         red=blue=green=0;
//         blue=color_num;
//    }
//    else if(color_change>6&&color_change<9)
//    {
//         color_change=0;
//         red=blue=green=0;
//         green=color_num;
//    }
}
 void my_timer2(lv_timer_t * timer)
{
    color_running();

     /* Set the LED pixel using RGB from 0 (0%) to 255 (100%) for each color */
    for (int i = 0; i < LED_STRIP_LED_NUMBERS; i++) {
        
        ESP_ERROR_CHECK(led_strip_set_pixel(led_strip, i, red, green, blue));
       
    }
    
    
   
            /* Refresh the strip to send data */
    ESP_ERROR_CHECK(led_strip_refresh(led_strip));
    //ESP_LOGI(TAG, "LED ON!");

}
 
 
 //********************************* */
void   LVGL_knob_event(void *event)
{
     ESP_LOGI(TAG, "HF---Read  %d",event);
    if(event==KNOB_LEFT)
    {
          HF_index=1;
       if(HF_ui_screen_id==1)
       {
       index2++;
       if(index2>=7)//只有6张图片
       index2=1;
       }
        else if(HF_ui_screen_id==2)
       {
            selected_index++;
            if(selected_index>options_max_num)
                 selected_index=0;
            lv_roller_set_selected(ui_Roller1,selected_index,LV_ANIM_ON);//旋钮带动滑轮转动
        }

    }
    else if(event==KNOB_RIGHT)
    {
          HF_index=1;
        if(HF_ui_screen_id==1)
        {
            index2--;
            if(index2<=0)
            index2=6;
        }
         else if(HF_ui_screen_id==2)
       {
            selected_index--;
            if(selected_index<0)
                 selected_index=options_max_num;
            lv_roller_set_selected(ui_Roller1,selected_index,LV_ANIM_ON);//旋钮带动滑轮转动
        }

    }
     if(HF_index==1)
    {

        HF_index=0;

        
        if(index2==1)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_1kaorou_png);
        else if(index2==2)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
        else if(index2==3)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
        else if(index2==4)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_4pisa_png);
        else if(index2==5)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_5liupai_png);
        else if(index2==6)
        {
           
            _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_6shutiao_png);
        }
       
   
    }
}

void   LVGL_button_event(void *event)
{
    static uint8_t last_event=BUTTON_PRESS_DOWN;
    ESP_LOGI(TAG, "HF---Read  %d",event);
    if(event==BUTTON_PRESS_DOWN)
    {
         ESP_LOGI(TAG,"BUTTON_PRESS_DOWN");
         

    }
    if(event==BUTTON_LONG_PRESS_HOLD)
    {
        if(HF_ui_screen_id==1)
        {
            HF_ui_screen_id=2;
            HF_index=0;
            last_event=BUTTON_LONG_PRESS_HOLD;
           
            _ui_screen_change(&ui_time, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_time_screen_init);

        

            return;
        }
    }

     if(event==BUTTON_PRESS_UP)
    {
        ESP_LOGI(TAG,"BUTTON_PRESS_UP");
        if(last_event==BUTTON_LONG_PRESS_HOLD)
        {
           last_event=BUTTON_PRESS_DOWN;
           return ;
        }
        else{

              
            if(HF_ui_screen_id==1)
            {   
            
                HF_ui_screen_id=3;
                _ui_screen_change(&ui_working, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_working_screen_init);
            }
            else if(HF_ui_screen_id==2)
            {
                
                selected_index = lv_roller_get_selected(ui_Roller1); // 获取当前选中的索引  
                ESP_LOGE(TAG, "ui_Roller1 ==%d",selected_index);
                _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, options[selected_index]);
                HF_ui_screen_id=1;
                _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);

            }
            else if(HF_ui_screen_id==3)
            {
            
                HF_ui_screen_id=1;
                _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);
            }
                
          

        }
      
    }

}
 
 

///////////////////// FUNCTIONS ////////////////////
void ui_event_background(lv_event_t * e)
{  
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {//滑动效果依然没有
        lv_indev_wait_release(lv_indev_get_act());
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
    }



    if(event_code == LV_EVENT_CLICKED) {//触摸点击
        index2++;
        if(index2>=7)
            index2=1;
        if(index2==1)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
        else if(index2==2)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
        else if(index2==3)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_4pisa_png);
        else if(index2==4)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_5liupai_png);
        else if(index2==5)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_6shutiao_png);
        else if(index2==6)
        {
           
            _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_1kaorou_png);
        }
    }
    
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        HF_ui_screen_id=2;
        _ui_screen_change(&ui_time, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_time_screen_init);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        HF_ui_screen_id=3;
        _ui_screen_change(&ui_working, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_working_screen_init);
    }
}
void ui_event_Button3(lv_event_t * e)
{
     

    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        HF_ui_screen_id=1;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    
    
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        HF_ui_screen_id=1;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
         selected_index = lv_roller_get_selected(ui_Roller1); // 获取当前选中的索引  
         HF_number= options2[selected_index];
        ESP_LOGE(TAG, "ui_Roller1 ==%d",selected_index);
        _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, options[selected_index]);
        HF_ui_screen_id=1;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_working_screen_init();
    ui_time_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
